### ISSUE TITLE
[5] Requests should not be marked as "Fulfilled" until the Distribution has been created

### ISSUE THREAD

**Issue by nihonjinrxs** [loyno-mathcs/diaper#12]
This is from rubyforgood/diaper#736. See details there.

This is an umbrella issue that will need to be split up into pieces that are more workable. In particular, [the checklist here](https://github.com/rubyforgood/diaper/issues/736#issuecomment-471410999) should be helpful in splitting this appropriately. Each issue resulting from the split will need to be independently estimated once that's done.

I'm happy to help if needed.

**Comment by Maddiefayee** [comment]
This has been split into 3 issues:

https://github.com/loyno-mathcs/diaper/issues/15
https://github.com/loyno-mathcs/diaper/issues/16
https://github.com/loyno-mathcs/diaper/issues/17
