### ISSUE TITLE
"Get the app working on your machine" (yes, this issue is for you!)

### ISSUE THREAD

**Issue by armahillo** [loyno-mathcs/diaper#5]
# Summary
Before you can work on the app, you have to get the app working!

 - Ensure you have ruby working (you may want to install https://rvm.io first), this app uses Ruby version 2.5.3 (check yours with: `ruby -v` at the command line)
 - Clone the repo to your dev environment
 - Get PostgreSQL running
 - Run `bin/update` from the app's root. -- the most likely reason this will fail is because your database has not yet been configured correctly. There's some info in the `README.md`, but you may need to search the Internet for more info 
 - Run `bundle exec rake` from the app's root. This will run the test suite -- you should see a bunch of text scroll by, and it should be almost all green. At the end, the test summary should say "0 failures".  (If you see nonzero failures, there will probably be a LOT of them -- it's ok to ^C out of the test run during the tests)

# Checklist
Once you've completed this, find your name on this list and check it off. 

**IMPORTANT** -- Rails is very community-oriented. Find someone else on your team who has not yet gotten the app working on their machine and pair up with them to get it going. 

## Team A

- [x] Emilie Blecker @eblecker
- [x] Eric Dax @ericsdax
- [x] Jessica Cao @JessicaKCao
- [x] Maddie Lemmond @madisonlemmond
- [x] Sky Gourley @Skyg21
- [x] Staffon Turley @StaffonTurley
- [x] Trevor Docherty @trevordocherty

## Team B

- [x] Jason LaHatte @jjlahatte
- [x] Joey Ruzevich @JoeyRuzevich
- [x] Madison Wood @Maddiefayee
- [x] Annie Delashmet @madelashmet
- [x] Quinton Liang @quintonliang
- [x] Randon Dupont @Randond
- [x] Ryan Blanchard @ryanbla

**Comment by nihonjinrxs** [comment]
If you are on **Windows 10**, using Windows Subsystem for Linux will likely make your experience easier. Here are some instructions for installing that:

1. Install WSL. Right-click on the Windows menu button and select "Windows PowerShell (Admin)" then type:
```
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```
You'll be asked to confirm in the command window that you want to install, and the machine will restart when you do.
2. Install Ubuntu 18.04. Once it's back up, re-open PowerShell as Admin, and type:
```
Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-1804 -OutFile Ubuntu.appx -UseBasicParsing
```
You may be asked to enter a UNIX username and password. Follow the instructions.
3. Install RVM and Ruby. Open the Ubuntu app, and you'll see a linux command line. Do the following:
```
sudo apt-get install gnupg dirmngr
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
\curl -sSL https://get.rvm.io | bash -s stable
```
Follow the instructions at the end of the output from the last command. You'll probably need to run a command starting with `source`.
4.  Use RVM to install Ruby 2.5.3
```
rvm install ruby-2.5.3
```
5. Confirm that Ruby is installed properly:
```
ruby -v
```

To install PostgreSQL, do the following:

1. Download and install postgres 10.6 64-bit from https://postgresql.org and follow the installation prompts. When asked for a password for the `postgres` user, provide one.

2. In Ubuntu, install the postgresql client libraries
```
sudo apt-get install libpq-dev postgresql-client-common postgresql-client-10
```

3. Test that your postgres installation is working
```
psql --host=localhost --port=5432 --user=postgres
> \l
... you should see a table of database names here, including postgres...
> \q
```

Ensure your git installation is configured correctly:

1. Check that git is installed via `which git` -- if you see a path to the git program, you're set. if not, you'll need to install git.

2. Configure your git installation by doing the following in Ubuntu (replacing the stuff in `< ... >` with the appropriate values):
```
git config --global user.name "<your name here>"
git config --global user.email "<your email here>"
git config --global core.autocrlf true
```

To setup the `diaper` app, do the following from the repo root directory (`.../diaper`):

1. Clone the repo from Github. Through Ubuntu, you can get to files on your disk drives through `/mnt`. For example, files at `C:\` will be available at `/mnt/c/`. Then change into the repo's root directory. (Be sure to replace `<location where you want your code>` below with an actual directory path.)
```
cd <location where you want your code>
git clone https://github.com/loyno-mathcs/diaper.git
cd diaper
```

2. Install the gem dependencies (note this one can take quite a while)
```
bundle install
```

3. Create your `.env` file with database account information. (Be sure to replace `<your password here>` below with the actual password you added during the postgresql installation.
```
echo "PG_USERNAME=postgres" > .env
echo "PG_PASSWORD=<your password here>" >> .env
```

4. Setup the database tables
```
bundle exec rails db:setup
./bin/update
```

5. Run the app to test that it works
```
bundle exec rails s
```
In browser, navigate to address listed (usually 0.0.0.0:3000 or similar)

To setup the `diaper` app, do the following from the repo root directory (`.../diaper`):

1. Clone the repo from Github. Through Ubuntu, you can get to files on your disk drives through `/mnt`. For example, files at `C:\` will be available at `/mnt/c/`. Then change into the repo's root directory. (Be sure to replace `<location where you want your code>` below with an actual directory path.)
```
cd <location where you want your code>
git clone https://github.com/loyno-mathcs/partner.git
cd partner
```

2. Install the gem dependencies (note this one can take quite a while)
```
bundle install
```

3. Create your `.env` file with database account information. (Be sure to replace `<your password here>` below with the actual password you added during the postgresql installation.
```
echo "PG_USERNAME=postgres" > .env
echo "PG_PASSWORD=<your password here>" >> .env
```

4. Setup the database tables
```
bundle exec rails db:setup
bundle exec rails db:seed
```

5. Run the app to test that it works
```
bundle exec rails s
```
In browser, navigate to address listed (usually 0.0.0.0:3000 or similar)

**Comment by nihonjinrxs** [comment]
On **MacOS**, you'll use the Terminal app to enter command line instructions.

1. You should be able to follow the instructions at https://rvm.io without issues.
2. Once RVM is installed, you can enter `rvm install ruby-2.5.3` to install the Ruby version needed.
3. You can install the PostgreSQL database by downloading the app at https://postgresapp.com/. This puts a little elephant icon in the upper menubar that has status of the postgres database and allows you to start `psql` in terminal. PostgreSQL version 10.5 or 10.6 is a reasonable choice at this time.
4. Ensure your git installation is configured correctly:
    1. Check that git is installed via `which git` -- if you see a path to the git program, you're set. if not, you'll need to install git.
    2. Configure your git installation by doing the following in Ubuntu (replacing the stuff in `< ... >` with the correct values):
    ```
    git config --global user.name "<your name here>"
    git config --global user.email "<your email here>"
    ```
5. You can follow the app setup instructions above.

**Comment by nihonjinrxs** [comment]
If you have problems, talk with your teammates and get things going. If you all still have trouble, I can help.

**Comment by nihonjinrxs** [comment]
Folks, if you are now comfortable with your environment setup and making progress on project work, please check your name off below. Once everyone has checked here, we'll close this issue. If you are unable to check your name off, please speak with me immediately so we can get your situation figured out.

# Team A
* [ ]  Emilie Blecker @eblecker
* [ ]  Eric Dax @ericsdax
* [ ]  Jessica Cao @JessicaKCao
* [ ]  Maddie Lemmond @madisonlemmond
* [ ]  Sky Gourley @Skyg21
* [ ]  Staffon Turley @StaffonTurley
* [ ]  Trevor Docherty @trevordocherty

# Team B
* [ ]  Jason LaHatte @jjlahatte
* [ ]  Joey Ruzevich @JoeyRuzevich
* [ ]  Madison Wood @Maddiefayee
* [ ]  Annie Delashmet @madelashmet
* [ ]  Quinton Liang @quintonliang
* [ ]  Randon Dupont @Randond
* [ ]  Ryan Blanchard @ryanbla
